In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/final_data.csv')
df

,Unnamed: 0,Price,Transmission,Power,Engine CC,Fuel_2.0,Class
0,0,30.619322,5.966102,94.033898,1497.169492,0,Trending
1,1,18.532143,5.714286,68.571429,1166.142857,0,Trending
2,2,31.242154,6.164835,89.461538,1537.406593,0,Trending
3,3,22.100000,5.615385,75.576923,1219.653846,0,Trending
4,4,47.848370,6.444444,126.111111,1995.777778,0,Trending
...,...,...,...,...,...,...,...
6087,6087,108.747195,7.853659,207.609756,2304.975610,1,Not trending
6088,6088,43.548516,1.354839,137.774193,2261.193548,0,Not trending
6089,6089,55.200000,6.000000,163.500000,2696.500000,0,Not trending
6090,6090,30.081000,4.000000,110.000000,2254.000000,0,Not trending
6091,6091,23.165158,3.947368,82.157895,1817.315789,0,Not trending

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X = df.iloc[:,1:6]
y = df["Class"]
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Applying the classifier
model = GaussianNB()
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.4938474159146842